### ISSUE TITLE
Incompatibility with {eepic}

### ISSUE THREAD

**Issue by pauloney** [rolfn/eso-pic#6]
I get an error when running the following example which seems to show an incompatibility between  `{eepic}` and `{showframe}`:

````
\documentclass{report}

\usepackage{eepic}
\usepackage{showframe}

\begin{document}
This is a test.
\end{document}
````

**Comment by rolfn** [comment]
The cause of the problem: `showframe` uses the ability to specify a dimension (number with unit or dimension register) for the  `\line` command, as the LaTeX kernel has offered for some time. `eepic` redefines `\line` so that only a dimensionless parameter is allowed. Therefore, the following example produces the same error without `showframe`:

```
\documentclass{report}

\usepackage{eepic}

\begin{document}

\begin{picture}(2cm,2cm)
   \put(0,0){
     \line(1,1){2.83cm}%
   }%
\end{picture}

This is a test.
\end{document}
```

A solution would probably be to load the `picture` package after `eepic`:

```
...
\usepackage{eepic}
\usepackage{picture}
...
```

However, you should consider whether it still makes sense to use the outdated `eepic` package these days. There are plenty of better alternatives, such as `pict2e`,  `tikz` or `pstricks`.
